/**
 * Posts localization: locale list, per-locale UI/SEO copy, and route mapping.
 *
 * Why:
 * - Belarusian posts live at `/posts/`, Russian at `/posts/ru/`.
 * - The site has no i18n library; for a handful of locales a small typed map is
 *   simpler and keeps all strings in one place.
 */
import {RouteName} from '@/router/routeNames'

export type PostLocale = 'be' | 'ru'

export const DEFAULT_LOCALE: PostLocale = 'be'
export const POST_LOCALES: PostLocale[] = ['be', 'ru']

// Why: Chromium ships no `be` locale data at all, so `Intl` silently formatted every
// Belarusian date as "Sep 21, 2026" in the browser while the prerendered HTML said
// "21 верасня 2026" — the text flipped on hydration. Both languages are formatted from
// these tables instead, in UTC, so a reader west of the meridian does not see the
// previous day either.
const monthNames: Record<PostLocale, string[]> = {
    be: [
        'студзеня', 'лютага', 'сакавіка', 'красавіка', 'мая', 'чэрвеня',
        'ліпеня', 'жніўня', 'верасня', 'кастрычніка', 'лістапада', 'снежня'
    ],
    ru: [
        'января', 'февраля', 'марта', 'апреля', 'мая', 'июня',
        'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'
    ]
}

export const formatPostDate = (locale: PostLocale, value: string) => {
    const date = new Date(value)
    if (Number.isNaN(date.getTime())) return value
    return `${date.getUTCDate()} ${monthNames[locale][date.getUTCMonth()]} ${date.getUTCFullYear()}`
}

// OpenGraph `og:locale` value per language.
export const ogLocale: Record<PostLocale, string> = {
    be: 'be_BY',
    ru: 'ru_RU'
}

// The author's name as each language spells it. The Latin spelling belongs to the CV
// and lives in `src/data/cv.json`; it also stays the site's name in search and shares.
export const authorName: Record<PostLocale, string> = {
    be: 'Уладзімір Бярнацкі',
    ru: 'Владимир Бернацкий'
}

// `<html lang>` / `hreflang` value per language.
export const htmlLang: Record<PostLocale, string> = {
    be: 'be',
    ru: 'ru'
}

export const indexRouteName: Record<PostLocale, RouteName> = {
    be: RouteName.Posts,
    ru: RouteName.PostsRu
}

export const postRouteName: Record<PostLocale, RouteName> = {
    be: RouteName.PostsPost,
    ru: RouteName.PostsRuPost
}

export const otherLocale: Record<PostLocale, PostLocale> = {
    be: 'ru',
    ru: 'be'
}

// URL path for a post / index in a given locale (used by SEO + sitemap parity).
// Per-language RSS feed, generated by `scripts/generate-feed.mjs`.
export const feedPath: Record<PostLocale, string> = {
    be: '/feed.xml',
    ru: '/feed.ru.xml'
}

export const indexPath: Record<PostLocale, string> = {
    be: '/posts/',
    ru: '/posts/ru/'
}

export const postPath = (locale: PostLocale, slug: string) =>
    locale === 'ru' ? `/posts/ru/${slug}/` : `/posts/${slug}/`

export type PostsCopy = {
    // Self-name of the language, used in the language switcher.
    langName: string
    // List page.
    eyebrow: string
    listTitle: string
    intro: string
    backHome: string
    // Post page.
    backToList: string
    toList: string
    notFoundTitle: string
    notFoundText: string
    switchLabel: string
    // End-of-post block: who wrote this, and where to go next.
    // The role line is not here: a job title reads in English in every language.
    authorNote: string
    cvCta: string
    moreTitle: string
    allPosts: string
    rssLabel: string
    // SEO / share.
    siteName: string
    titleSuffix: string
    shareHint: string
    seoNotFoundTitle: string
    seoNotFoundDescription: string
}

export const postsCopy: Record<PostLocale, PostsCopy> = {
    be: {
        langName: 'Беларуская',
        eyebrow: 'Нататкі',
        listTitle: 'Запісы',
        intro: 'Невялікія нататкі пра жыццё, творчасць і не толькі.',
        backHome: 'Назад',
        backToList: 'Назад да запісаў',
        toList: 'Да спісу запісаў',
        notFoundTitle: 'Запіс не знойдзены',
        notFoundText: 'Старонка недаступная. Абяры іншы запіс са спісу.',
        switchLabel: 'Мова',
        authorNote: 'Пішу пра ровар, здымкі і ўласныя невялікія праекты.',
        cvCta: 'Паглядзець рэзюмэ',
        moreTitle: 'Яшчэ нататкі',
        allPosts: 'Усе запісы',
        rssLabel: 'RSS',
        siteName: 'Uladzimir Biarnatski',
        titleSuffix: 'bvvell.site',
        shareHint: 'Поўны тэкст і прыклады — на маім сайце.',
        seoNotFoundTitle: 'Запіс не знойдзены — Нататкі — Uladzimir Biarnatski',
        seoNotFoundDescription: 'Старонка недаступная.'
    },
    ru: {
        langName: 'Русский',
        eyebrow: 'Заметки',
        listTitle: 'Записи',
        intro: 'Небольшие заметки о жизни, творчестве и не только.',
        backHome: 'Назад',
        backToList: 'Назад к записям',
        toList: 'К списку записей',
        notFoundTitle: 'Запись не найдена',
        notFoundText: 'Страница недоступна. Выбери другую запись из списка.',
        switchLabel: 'Язык',
        authorNote: 'Пишу про велосипед, съёмки и свои небольшие проекты.',
        cvCta: 'Посмотреть резюме',
        moreTitle: 'Ещё заметки',
        allPosts: 'Все записи',
        rssLabel: 'RSS',
        siteName: 'Uladzimir Biarnatski',
        titleSuffix: 'bvvell.site',
        shareHint: 'Полный текст и примеры — на моём сайте.',
        seoNotFoundTitle: 'Запись не найдена — Заметки — Uladzimir Biarnatski',
        seoNotFoundDescription: 'Страница недоступна.'
    }
}

// Belarusian is the default; anything else (home/CV) is English at the document level.
export const isPostLocale = (value: unknown): value is PostLocale =>
    value === 'be' || value === 'ru'
